name: Nightly Develop Sync

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync develop with main
        run: |
          git fetch origin main
          git rebase origin/main
          if [ $? -eq 0 ]; then
            git push origin develop --force
          else
            echo "Rebase failed - conflicts need to be resolved manually"
            exit 1
          fi 